//! Build script for the vendored `MicroQuickJS` engine.
//!
//! Pipeline (mirrors the upstream Makefile):
//! 1. Compile `mquickjs_build.c` + `csrc/mh_stdlib.c` into a host tool.
//! 2. Run it twice: `-a` emits `mquickjs_atom.h`, plain run emits
//!    `mh_stdlib.h` (serialized stdlib ROM + `js_stdlib` def).
//! 3. Compile the engine (`mquickjs.c cutils.c dtoa.c libm.c`) plus
//!    `csrc/mh_shim.c` into `libmhquickjs.a` and link it into the crate.

use std::env;
use std::path::PathBuf;
use std::process::Command;

// C flags mirroring the upstream Makefile.
const ENGINE_FLAGS: &[&str] = &["-D_GNU_SOURCE", "-fno-math-errno", "-fno-trapping-math"];

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    let vendor = manifest.join("vendor/mquickjs");
    let csrc = manifest.join("csrc");

    println!(
        "cargo:rerun-if-changed={}",
        csrc.join("mh_stdlib.c").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        csrc.join("mh_shim.c").display()
    );
    println!("cargo:rerun-if-changed={}", vendor.display());
    println!("cargo:rerun-if-changed=build.rs");

    let target = env::var("TARGET").expect("TARGET");
    let host = env::var("HOST").expect("HOST");
    assert!(
        target == host,
        "mh-quickjs-sys: cross-compilation is not supported in v0.1 \
         (stdlib tables are generated by a host tool); TARGET={target} HOST={host}"
    );
    assert!(
        target.contains("darwin") || target.contains("linux"),
        "mh-quickjs-sys: unsupported target OS for {target}"
    );

    // 1. Host stdlib build tool.
    cc::Build::new()
        .file(vendor.join("mquickjs_build.c"))
        .file(csrc.join("mh_stdlib.c"))
        .include(&vendor)
        .flag("-O2")
        .opt_level(2)
        .compile("mh_stdlib_build");

    let tool = out.join("mh_stdlib_build");
    let lib = out.join("libmh_stdlib_build.a");
    let compiler = cc::Build::new().get_compiler();
    let link = Command::new(compiler.path())
        .arg(&lib)
        .arg("-o")
        .arg(&tool)
        .arg("-lm")
        .status()
        .expect("failed to link mh_stdlib_build host tool");
    assert!(link.success(), "linking mh_stdlib_build failed");

    // 2. Generate the atom header and the stdlib ROM table.
    let gendir = out.join("gen");
    std::fs::create_dir_all(&gendir).expect("create gen dir");

    let atoms = Command::new(&tool)
        .arg("-a")
        .output()
        .expect("run stdlib tool (-a)");
    assert!(atoms.status.success(), "stdlib tool -a failed");
    std::fs::write(gendir.join("mquickjs_atom.h"), &atoms.stdout).expect("write mquickjs_atom.h");

    let table = Command::new(&tool).output().expect("run stdlib tool");
    assert!(table.status.success(), "stdlib tool failed");
    std::fs::write(gendir.join("mh_stdlib.h"), &table.stdout).expect("write mh_stdlib.h");

    // 3. Compile the engine + shim.
    cc::Build::new()
        .file(vendor.join("mquickjs.c"))
        .file(vendor.join("cutils.c"))
        .file(vendor.join("dtoa.c"))
        .file(vendor.join("libm.c"))
        .file(csrc.join("mh_shim.c"))
        .include(&vendor)
        .include(&gendir)
        .flags(ENGINE_FLAGS)
        .flag("-Os") // CONFIG_SMALL in the upstream Makefile
        .compile("mhquickjs");

    println!("cargo:rustc-link-lib=static=mhquickjs");
    println!("cargo:rustc-link-lib=m");
}
